In [1]:
import numpy as np

In [2]:
arr= np.array[[1,2,3],[4,5,6],[7,8,9]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [3]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr.[1,2]

SyntaxError: invalid syntax (<ipython-input-5-e9bacc3e7bce>, line 1)

In [6]:
arr[1,2]

6

In [7]:
arr[:][:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr[:][:1]

array([[1, 2, 3]])

In [9]:
arr[:2][:1]

array([[1, 2, 3]])

In [10]:
arr[:0][:1]

array([], shape=(0, 3), dtype=int64)

In [11]:
arr[:2,:1]

array([[1],
       [4]])

In [12]:
arr[:2,:2]

array([[1, 2],
       [4, 5]])

In [13]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr[:3,:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr[1:3,:2]

array([[4, 5],
       [7, 8]])

In [16]:
arr[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [17]:
arr[2,:2]

array([7, 8])

In [18]:
arr[2,0:3]

array([7, 8, 9])

In [19]:
arr[2,2:3]

array([9])

In [20]:
arr[:2][:1]

array([[1, 2, 3]])

In [21]:
arr[:2,:1]

array([[1],
       [4]])

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr[:2][:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr[:1][:1]

array([[1, 2, 3]])

In [25]:
arr[1:3,:2]

array([[4, 5],
       [7, 8]])

In [26]:
arr[1:3,2]

array([6, 9])

In [27]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr.shape()

TypeError: 'tuple' object is not callable

In [29]:
arr.shape(1)

TypeError: 'tuple' object is not callable

In [30]:
arr.shape[]

SyntaxError: invalid syntax (<ipython-input-30-2ffd9da6e10a>, line 1)

In [31]:
arr.shape[1]

3

In [32]:
arr.shape[,2]

SyntaxError: invalid syntax (<ipython-input-32-113cf8ff78ff>, line 1)

In [33]:
arr.shape[2]

IndexError: tuple index out of range

In [34]:
arr.shape[0]

3

In [36]:
ar=np.zeros(1)

In [37]:
ar=np.zeros(1)

In [38]:
ar=np.zeros(2)

In [39]:
ar=np.zeros(1,2)

TypeError: data type not understood

In [40]:
ar=np.zeros((1,2))

In [41]:
ar

array([[0., 0.]])

In [42]:
ar=np.zeros(1)
ar

array([0.])

In [43]:
ar=np.zeros((1,2))

In [44]:
ar

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
ar=np.zeros((1,2),int)

In [46]:
ar

array([[0, 0]])

In [47]:
ar=np.zeros((1,2))



In [48]:
ar=np.zeros((10,10),int)

In [49]:
ar

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [50]:
ar[1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
ar[1]=2

In [52]:
ar

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [53]:
ar[1,2]=3
ar

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 3, 2, 2, 2, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [54]:
ar[[9:10],[9:10]]
ar

SyntaxError: invalid syntax (<ipython-input-54-4d168d8b4f10>, line 1)

In [55]:
ar[(9:10),(9:10)]
ar


SyntaxError: invalid syntax (<ipython-input-55-b851e043c46a>, line 1)

In [56]:
ar[[8:9],[8:9]]
ar


SyntaxError: invalid syntax (<ipython-input-56-b48aa41c2281>, line 1)

In [57]:
ar


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 3, 2, 2, 2, 2, 2, 2, 2],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [58]:
ar[(8:9),(8:9)]
ar

SyntaxError: invalid syntax (<ipython-input-58-931c823a9acf>, line 1)

In [59]:
ar[2]=5
ar

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 3, 2, 2, 2, 2, 2, 2, 2],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [60]:
ar[8:9,8:9]=2
ar

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 3, 2, 2, 2, 2, 2, 2, 2],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [61]:
ar[7:9,8:9]=2
ar

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 3, 2, 2, 2, 2, 2, 2, 2],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [62]:
ar[7:9,7:9]=2
ar


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 3, 2, 2, 2, 2, 2, 2, 2],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [63]:
ar

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [2, 2, 3, 2, 2, 2, 2, 2, 2, 2],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 2, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [64]:
ar[9:11,0:2]=21
ar


array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  2,  3,  2,  2,  2,  2,  2,  2,  2],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  2,  2,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  2,  2,  0],
       [21, 21,  0,  0,  0,  0,  0,  0,  0,  0]])

In [65]:
ar[8:10,0:2]=21
ar

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  2,  3,  2,  2,  2,  2,  2,  2,  2],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  2,  2,  0],
       [21, 21,  0,  0,  0,  0,  0,  2,  2,  0],
       [21, 21,  0,  0,  0,  0,  0,  0,  0,  0]])

In [66]:
ar.swapaxes(1,2)
ar

AxisError: axis2: axis 2 is out of bounds for array of dimension 2

In [67]:
ar.swapaxes(0,1)
ar


array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 2,  2,  3,  2,  2,  2,  2,  2,  2,  2],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  2,  2,  0],
       [21, 21,  0,  0,  0,  0,  0,  2,  2,  0],
       [21, 21,  0,  0,  0,  0,  0,  0,  0,  0]])

In [68]:
ar.swapaxes(0,2)
ar


AxisError: axis2: axis 2 is out of bounds for array of dimension 2